syntax = "proto3";

package pix;

service PixService {
  rpc ProcessPix (PixRequest) returns (PixResponse) {}
  rpc GetTransactionStatus (StatusRequest) returns (StatusResponse) {}
}

message PixRequest {
  string fromAccount = 1;
  string toAccount = 2;
  double amount = 3;
  string description = 4;
}

message PixResponse {
  string transaction_id = 1;
  string status = 2;
  string error = 3;
}

message StatusRequest {
  string transaction_id = 1;
}

message StatusResponse {
  string transaction_id = 1;
  string from_account = 2;
  string to_account = 3;
  double amount = 4;
  string description = 5;
  string status = 6;
  string error = 7;
  string created_at = 8;
} 