// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: pix.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import Long = require("long");

export const protobufPackage = "pix";

export interface ProcessPixRequest {
  fromAccount: string;
  toAccount: string;
  amount: number;
}

export interface ProcessPixResponse {
  transactionId: string;
  status: string;
}

function createBaseProcessPixRequest(): ProcessPixRequest {
  return { fromAccount: "", toAccount: "", amount: 0 };
}

export const ProcessPixRequest: MessageFns<ProcessPixRequest> = {
  encode(message: ProcessPixRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromAccount !== "") {
      writer.uint32(10).string(message.fromAccount);
    }
    if (message.toAccount !== "") {
      writer.uint32(18).string(message.toAccount);
    }
    if (message.amount !== 0) {
      writer.uint32(25).double(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessPixRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessPixRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fromAccount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toAccount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessPixRequest {
    return {
      fromAccount: isSet(object.fromAccount) ? globalThis.String(object.fromAccount) : "",
      toAccount: isSet(object.toAccount) ? globalThis.String(object.toAccount) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: ProcessPixRequest): unknown {
    const obj: any = {};
    if (message.fromAccount !== "") {
      obj.fromAccount = message.fromAccount;
    }
    if (message.toAccount !== "") {
      obj.toAccount = message.toAccount;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProcessPixRequest>, I>>(base?: I): ProcessPixRequest {
    return ProcessPixRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProcessPixRequest>, I>>(object: I): ProcessPixRequest {
    const message = createBaseProcessPixRequest();
    message.fromAccount = object.fromAccount ?? "";
    message.toAccount = object.toAccount ?? "";
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseProcessPixResponse(): ProcessPixResponse {
  return { transactionId: "", status: "" };
}

export const ProcessPixResponse: MessageFns<ProcessPixResponse> = {
  encode(message: ProcessPixResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionId !== "") {
      writer.uint32(10).string(message.transactionId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessPixResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessPixResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProcessPixResponse {
    return {
      transactionId: isSet(object.transactionId) ? globalThis.String(object.transactionId) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: ProcessPixResponse): unknown {
    const obj: any = {};
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProcessPixResponse>, I>>(base?: I): ProcessPixResponse {
    return ProcessPixResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProcessPixResponse>, I>>(object: I): ProcessPixResponse {
    const message = createBaseProcessPixResponse();
    message.transactionId = object.transactionId ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

export type PixServiceService = typeof PixServiceService;
export const PixServiceService = {
  processPix: {
    path: "/pix.PixService/ProcessPix",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ProcessPixRequest) => Buffer.from(ProcessPixRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ProcessPixRequest.decode(value),
    responseSerialize: (value: ProcessPixResponse) => Buffer.from(ProcessPixResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ProcessPixResponse.decode(value),
  },
} as const;

export interface PixServiceServer extends UntypedServiceImplementation {
  processPix: handleUnaryCall<ProcessPixRequest, ProcessPixResponse>;
}

export interface PixServiceClient extends Client {
  processPix(
    request: ProcessPixRequest,
    callback: (error: ServiceError | null, response: ProcessPixResponse) => void,
  ): ClientUnaryCall;
  processPix(
    request: ProcessPixRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ProcessPixResponse) => void,
  ): ClientUnaryCall;
  processPix(
    request: ProcessPixRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ProcessPixResponse) => void,
  ): ClientUnaryCall;
}

export const PixServiceClient = makeGenericClientConstructor(PixServiceService, "pix.PixService") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): PixServiceClient;
  service: typeof PixServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}

export const PIX_SERVICE_NAME = "PixService";
export const PixServiceDesc = {
  serviceName: "PixService",
  methods: {
    ProcessPix: {
      methodName: "ProcessPix",
      requestStream: false,
      responseStream: false,
      requestType: ProcessPixRequest,
      responseType: ProcessPixResponse,
    },
  },
};
